# Docker Compose override for development environment
version: '3.8'

services:
  # Development Web GUI with hot reload
  web-gui:
    build:
      target: development  # Use development stage
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./app:/app/app:ro  # Mount source for hot reload
      - ./components:/app/components:ro
      - ./lib:/app/lib:ro
    command: npm run dev
    
  # Development Web GUI Node Backend
  web-gui-node:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ../web-gui-node/server.js:/app/server.js:ro
      - ../web-gui-node/routes:/app/routes:ro
      - ../web-gui-node/lib:/app/lib:ro
    command: npm run dev
    
  # Development ComfyUI with debugging
  comfyui:
    build:
      target: development
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: python main.py --listen 0.0.0.0 --port 8188 --verbose
    
  # Development Main Python App
  dinoair-main:
    build:
      target: development
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ../start.py:/app/start.py:ro
      - ../lib:/app/lib:ro
    command: python start.py --debug
    profiles:
      - development