# ESLint Security Analysis workflow for SARIF reporting
# Provides security-focused ESLint scanning with SARIF output
# More details at https://github.com/eslint/eslint

name: ESLint Security Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '42 16 * * 1'

jobs:
  eslint-sarif:
    name: ESLint SARIF Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web-gui/package-lock.json

      - name: Install dependencies
        working-directory: ./web-gui
        run: npm ci

      - name: Run ESLint with SARIF output
        working-directory: ./web-gui
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint . \
            --config .eslintrc.js \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload ESLint results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: web-gui/eslint-results.sarif
          wait-for-processing: true
