name: Super-Linter Comprehensive

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  DEFAULT_BRANCH: master

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v8.0.0
        env:
          DEFAULT_BRANCH: ${{ env.DEFAULT_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Validation settings
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_BASH: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          VALIDATE_XML: true
          
          # Configuration files
          TYPESCRIPT_ES_CONFIG_FILE: web-gui/.eslintrc.json
          JAVASCRIPT_ES_CONFIG_FILE: web-gui/.eslintrc.json
          PYTHON_BLACK_CONFIG_FILE: .python-black
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
          YAML_CONFIG_FILE: .yamllint.yml
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
          
          # Filtering
          FILTER_REGEX_EXCLUDE: '.*/(node_modules|\.git|\.github|build|dist|coverage|\.next|\.vscode|\.idea|__pycache__|\.pytest_cache)/.*'
          IGNORE_GITIGNORED_FILES: true
          
          # Output settings
          CREATE_LOG_FILE: true
          LOG_LEVEL: INFO
          SUPPRESS_POSSUM: true
          
          # Disable problematic linters for this codebase
          VALIDATE_JSCPD: false
          VALIDATE_NATURAL_LANGUAGE: false
